/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libRoundRobin_RoundRobin */

#ifndef _Included_libRoundRobin_RoundRobin
#define _Included_libRoundRobin_RoundRobin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libRoundRobin_RoundRobin
 * Method:    procesoRoundRobin
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libRoundRobin_RoundRobin_procesoRoundRobin
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
